name = "a10-hairsalon-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = []

[[d1_databases]]
binding = "DB"
database_name = "a10-hairsalon"
database_id = "local-dev-db"

[env.production]
name = "a10-hairsalon-api-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "a10-hairsalon-prod"
database_id = "4ee369b0-85de-46ac-8173-06a5f0e9ecfe"
