name = "a10-hairsalon-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = []

[[d1_databases]]
binding = "DB"
database_name = "a10-hairsalon"
database_id = "local"

[env.production]
name = "a10-hairsalon-api-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "a10-hairsalon-prod"
database_id = "TODO_SET_IN_ENV"
